import type { Metadata } from "next";
import { roboto } from "../../public/fonts/Roboto";
import "./globals.css";
import Providers from "@/lib/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <Providers>
        <body className={roboto.variable}>{children}</body>
      </Providers>
    </html>
  );
}

// lds.com/ 